-- MySQL Script generated by MySQL Workbench
-- 05/09/18 14:24:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CIDADE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUPERMERCADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SUPERMERCADO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SUPERMERCADO` (
  `codigo` INT NOT NULL,
  `endereço` VARCHAR(45) NULL,
  `CIDADE_codigo` INT NOT NULL,
  INDEX `fk_SUPERMERCADO_Cidade_idx` (`CIDADE_codigo` ASC),
  PRIMARY KEY (`codigo`),
  CONSTRAINT `fk_SUPERMERCADO_Cidade`
    FOREIGN KEY (`CIDADE_codigo`)
    REFERENCES `mydb`.`CIDADE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FORNECEDOR` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDOR` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PRODUTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `codigo de barras` INT NOT NULL,
  `descrição` VARCHAR(45) NULL,
  `preço compra` FLOAT NULL,
  `preço venda` FLOAT NULL,
  `quantidade estoque` INT NULL,
  `FORNECEDOR_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo de barras`),
  INDEX `fk_PRODUTO_FORNECEDOR1_idx` (`FORNECEDOR_codigo` ASC),
  CONSTRAINT `fk_PRODUTO_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_codigo`)
    REFERENCES `mydb`.`FORNECEDOR` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereço` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TELEFONE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE` (
  `codigo` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `CLIENTE_codigo` INT NOT NULL,
  `FORNECEDOR_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `FORNECEDOR_codigo`),
  INDEX `fk_TELEFONE_CLIENTE1_idx` (`CLIENTE_codigo` ASC),
  INDEX `fk_TELEFONE_FORNECEDOR1_idx` (`FORNECEDOR_codigo` ASC),
  CONSTRAINT `fk_TELEFONE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo`)
    REFERENCES `mydb`.`CLIENTE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TELEFONE_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_codigo`)
    REFERENCES `mydb`.`FORNECEDOR` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUPERMERCARDO/PRODUTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SUPERMERCARDO/PRODUTO` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SUPERMERCARDO/PRODUTO` (
  `SUPERMERCADO_codigo` INT NOT NULL,
  `PRODUTO_codigo de barras` INT NOT NULL,
  PRIMARY KEY (`SUPERMERCADO_codigo`, `PRODUTO_codigo de barras`),
  INDEX `fk_SUPERMERCADO_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_codigo de barras` ASC),
  INDEX `fk_SUPERMERCADO_has_PRODUTO_SUPERMERCADO1_idx` (`SUPERMERCADO_codigo` ASC),
  CONSTRAINT `fk_SUPERMERCADO_has_PRODUTO_SUPERMERCADO1`
    FOREIGN KEY (`SUPERMERCADO_codigo`)
    REFERENCES `mydb`.`SUPERMERCADO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SUPERMERCADO_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codigo de barras`)
    REFERENCES `mydb`.`PRODUTO` (`codigo de barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COMPRA` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA` (
  `PRODUTO_codigo de barras` INT NOT NULL,
  `CLIENTE_codigo` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`PRODUTO_codigo de barras`, `CLIENTE_codigo`),
  INDEX `fk_PRODUTO_has_CLIENTE_CLIENTE1_idx` (`CLIENTE_codigo` ASC),
  INDEX `fk_PRODUTO_has_CLIENTE_PRODUTO1_idx` (`PRODUTO_codigo de barras` ASC),
  CONSTRAINT `fk_PRODUTO_has_CLIENTE_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codigo de barras`)
    REFERENCES `mydb`.`PRODUTO` (`codigo de barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTO_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo`)
    REFERENCES `mydb`.`CLIENTE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
