-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FILIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FILIAL` (
  `codigo` INT NOT NULL,
  `endereco` VARCHAR(45) NULL,
  `CIDADE_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_FILIAL_CIDADE_idx` (`CIDADE_codigo` ASC),
  CONSTRAINT `fk_FILIAL_CIDADE`
    FOREIGN KEY (`CIDADE_codigo`)
    REFERENCES `mydb`.`CIDADE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FORNECEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FORNECEDOR` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTO` (
  `codigo_barras` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `preco_compra` FLOAT NULL,
  `preco_venda` FLOAT NULL,
  `quantidade_estoque` INT NULL,
  `FORNECEDOR_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo_barras`),
  INDEX `fk_PRODUTO_FORNECEDOR1_idx` (`FORNECEDOR_codigo` ASC),
  CONSTRAINT `fk_PRODUTO_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_codigo`)
    REFERENCES `mydb`.`FORNECEDOR` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FILIAL/PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FILIAL/PRODUTO` (
  `FILIAL_codigo` INT NOT NULL,
  `PRODUTO_codigo_barras` INT NOT NULL,
  PRIMARY KEY (`FILIAL_codigo`, `PRODUTO_codigo_barras`),
  INDEX `fk_FILIAL_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_codigo_barras` ASC),
  INDEX `fk_FILIAL_has_PRODUTO_FILIAL1_idx` (`FILIAL_codigo` ASC),
  CONSTRAINT `fk_FILIAL_has_PRODUTO_FILIAL1`
    FOREIGN KEY (`FILIAL_codigo`)
    REFERENCES `mydb`.`FILIAL` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FILIAL_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codigo_barras`)
    REFERENCES `mydb`.`PRODUTO` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `idade` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TELEFONE` (
  `codigo` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `CLIENTE_codigo` INT NULL,
  `FORNECEDOR_codigo` INT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_TELEFONE_CLIENTE1_idx` (`CLIENTE_codigo` ASC),
  INDEX `fk_TELEFONE_FORNECEDOR1_idx` (`FORNECEDOR_codigo` ASC),
  CONSTRAINT `fk_TELEFONE_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo`)
    REFERENCES `mydb`.`CLIENTE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TELEFONE_FORNECEDOR1`
    FOREIGN KEY (`FORNECEDOR_codigo`)
    REFERENCES `mydb`.`FORNECEDOR` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA` (
  `CLIENTE_codigo` INT NOT NULL,
  `PRODUTO_codigo_barras` INT NOT NULL,
  `data` DATE NULL,
  `hora` TIME NULL,
  PRIMARY KEY (`CLIENTE_codigo`, `PRODUTO_codigo_barras`),
  INDEX `fk_CLIENTE_has_PRODUTO_PRODUTO1_idx` (`PRODUTO_codigo_barras` ASC),
  INDEX `fk_CLIENTE_has_PRODUTO_CLIENTE1_idx` (`CLIENTE_codigo` ASC),
  CONSTRAINT `fk_CLIENTE_has_PRODUTO_CLIENTE1`
    FOREIGN KEY (`CLIENTE_codigo`)
    REFERENCES `mydb`.`CLIENTE` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PRODUTO_PRODUTO1`
    FOREIGN KEY (`PRODUTO_codigo_barras`)
    REFERENCES `mydb`.`PRODUTO` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
